spring:
  application:
    name: employee-security
jwt:
  secret: VGhpcy1pcy1hLXN1cGVyLXNlY3JldC1rZXktMTIzNDU2Nzg5MDEyMzQ1Ng==
  expiration: 3600000

server:
  port: 8081
  servlet:
    context-path: /api/v1

